FinalProject/Controllers/CategoryController.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalProject.Controllers
{
    public class CategoryController : Controller
    {
        AppDbContext db = new AppDbContext();

     

        public ActionResult Index()
        {
            var query = db.Categories.ToList();

            return View(query);
        }

      

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category c)
        {
            if (ModelState.IsValid)
            {
                Category cat = new Category();
                cat.Name = c.Name;
                db.Categories.Add(cat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "Not Inserted Category";
            }
            return View();
        }

      

        public ActionResult Edit(int id)
        {
            var query = db.Categories.SingleOrDefault(m => m.CategoryId == id);
            return View(query);
        }

        [HttpPost]
        public ActionResult Edit(Category c)
        {
            try
            {

                db.Entry(c).State = (System.Data.Entity.EntityState)EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msg"] = ex;
            }
            return RedirectToAction("Index");
        }

      

        public ActionResult Delete(int id)
        {
            var query = db.Categories.SingleOrDefault(m => m.CategoryId == id);
            db.Categories.Remove(query);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



      
    }
}

FinalProject/Controllers/ProductsController.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalProject.Controllers
{
    public class ProductsController : Controller
    {
        AppDbContext db = new AppDbContext();

      

        public ActionResult Index()
        {
            var query = db.Products.ToList();
            return View(query);
        }

     

        public ActionResult Create()
        {
            List<Category> list = db.Categories.ToList();
            ViewBag.CatList = new SelectList(list, "CategoryId", "Name");
            return View();
        }



        [HttpPost]
        public ActionResult Create(Product p, HttpPostedFileBase Image)
        {
            List<Category> list = db.Categories.ToList();
            ViewBag.CatList = new SelectList(list, "CategoryId", "Name");


            if (ModelState.IsValid)
            {


                Product pro = new Product();
                pro.Name = p.Name;
                pro.Description = p.Description;
                pro.Unit = p.Unit;
                pro.Image = Image.FileName.ToString();
                pro.CategoryId = p.CategoryId;

                //image upload
                var folder = Server.MapPath("~/Uploads/");
                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));

                db.Products.Add(pro);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "Product Not Upload";
            }
            return View();
        }


      

        public ActionResult Edit(int id)
        {

            List<Category> list = db.Categories.ToList();
            ViewBag.CatList = new SelectList(list, "CategoryId", "Name");

            var query = db.Products.SingleOrDefault(m => m.ProductId == id);

            return View(query);
        }


        [HttpPost]
        public ActionResult Edit(Product p, HttpPostedFileBase Image)
        {
            List<Category> list = db.Categories.ToList();
            ViewBag.CatList = new SelectList(list, "CategoryId", "Name");

            try
            {

                p.Image = Image.FileName.ToString();
                var folder = Server.MapPath("~/Uploads/");
                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));
                db.Entry(p).State = (System.Data.Entity.EntityState)EntityState.Modified;
                db.SaveChanges();

            }
            catch (Exception ex)
            {
                TempData["msg"] = ex;
            }

            return RedirectToAction("Index");

        }

       

        public ActionResult Delete(int id)
        {
            var query = db.Products.SingleOrDefault(m => m.ProductId == id);
            db.Products.Remove(query);

            db.SaveChanges();


            return RedirectToAction("Index");

        }

       
    }
}

FinalProject/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>@ViewBag.tittle </title>

</head>
<body>


    <!-- menu start -->
    <nav class="main-menu">
        <ul>



            @if (!User.Identity.IsAuthenticated)
            {

                <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="@Url.Action("Login","Account")" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="@Url.Action("Register", "Account")" class="nav-link">Register</a></li>
                if (TempData["cart"] != null)
                {
                    TempData.Keep();
                    <li class="nav-item cta cta-colored"><a href="@Url.Action("Checkout","Home")" class="nav-link"><span class="icon-shopping_cart"></span>[@TempData["item_count"]]</a></li>
                }

            } @if (User.Identity.IsAuthenticated)
            {

                if (User.IsInRole("1"))
                {
                    <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>

                    <li class="nav-item "><span class="nav-link">Welcome to @Session["User"]</span></li>


                    <li>
                        <a href="@Url.Action("Index", "Products")">Categories</a>
                        <ul class="sub-menu">
                            <li><a href="@Url.Action("Create", "Category")">Add Category</a></li>
                            <li><a href="@Url.Action("Index", "Category")">View Categories</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Products")">Products</a>
                        <ul class="sub-menu">
                            <li><a href="@Url.Action("Create", "Products")">Add Product</a></li>
                            <li><a href="@Url.Action("Index", "Products")">View Products</a></li>
                        </ul>
                    </li>




                    <li class="nav-item"><a href="@Url.Action("GetAllUser", "Home")" class="nav-link">Users</a></li>
                    <li class="nav-item"><a href="@Url.Action("GetAllOrderDetail", "Home")" class="nav-link">Orders</a></li>
                    <li class="nav-item"><a href="@Url.Action("Signout","Account")" class="nav-link">Logout</a></li>
                }
                if (User.IsInRole("2"))
                {

                    <li class="nav-item "><span class="nav-link">Welcome to @Session["User"]</span></li>
                    <li class="nav-item"><a href="@Url.Action("OrderDetail", "Home", new { id = @Session["uid"] })" class="nav-link">Orders</a></li>
                    if (TempData["cart"] != null)
                    {
                        TempData.Keep();
                        <li class="nav-item cta cta-colored"><a href="@Url.Action("Checkout","Home")" class="nav-link"><span class="icon-shopping_cart"></span>[@TempData["item_count"]]</a></li>

                    }

                    <li class="nav-item"><a href="@Url.Action("Signout","Account")" class="nav-link">Logout</a></li>
                }
            }

        </ul>




    </nav>












    @RenderBody()


</body>
</html>